### ISSUE TITLE
<우연적 속성이 불가능한 표현인가?> / p.237

### ISSUE THREAD

**Issue by kimkyunghun3** [5th-book-club/The-Essence-Of-Object-Orientation#11]
우연적 속성을 객체지향에서 표현할 수 없다고 하는데
본질적인 객체에서 상태를 변하는 것을 우연적 속성으로 볼수는 없는 것인가?
예를 들어 사람 객체가 회사원의 상태를 가진다는 것은 우연적 속성에 속하는 것일까?

**Comment by doogie97** [comment]
<B조>
- 두기&에디: 에디의 생각에 동의, 상태로 표현한다면 우연적인 속성도 충분히 표현 할 수 있을 것이라고 생각
```swift
protocol Person {
    var name: String { get } // 본질적인 속성
}

class Eddy: Person {
    var name: String = "에디"
    var job: String = "캠퍼" // 우연적인 속성
}
```
- 파프리: 객체를 바라보는 사람에 따라 기준이 다를 것 같다(누구는 a라는 속성을 A라는 객체의 본질로 볼 것이도 누구는 아닐 수도 있고...)
- 쿼카&마이노: 우연적인 속성은 추상화를 함에 있어서 필요한 부분이 아니니까 공통적인 속성은 잘 추려내서 추상화를 잘 할수 있도록 하라 라는 말을 하기 위함이 아닐까 싶다

**Comment by westeastyear** [comment]
- 그럼피: 우연적 속성은 표현을 할 필요가 없다. 표현을 하지 않음으로서 동일한 범주에 속하는 객체들을 묶을 수 있다고 생각합니다.
- 티아나: 협력에서 필요한 것만 표현하면 되는데, 협력에서 메인 역할을 하지 못하는 게 이유라고 생각합니다.
- 레드: 메인이 아니라는 것이 단순화 과정에서 탈락한 애들을 의미한다고 생각합니다.
