### ISSUE TITLE
<클래스간의 위임이란?> / p.243

### ISSUE THREAD

**Issue by kimkyunghun3** [5th-book-club/The-Essence-Of-Object-Orientation#12]
‘클래스간의 위임이 어떤 객체의 클래스가 수신된 메시지를 이해할 수 없다면 메시지를 부모 클래스로 위임한다’고 하는데 
어떻게 위임할 수 있는 것이며 위임한다는 것이 대신 해결해준다는 의미인것인지?

**Comment by FirstDo** [comment]
근데 저는 자식클래스가 메시지를 이해할 수 없다는거 부터 이해가 안되요
부모클래스의 모든걸 다 상속받았는데, 왜 이해를 못하나요?
부모보다 자식이 더 기능이 많잖아요..

override 매서드에서, super를 호출하는걸 의미하는걸까요?

**Comment by llingo** [comment]
자식 클래스에서 메서드를 오버라이딩을 하지 않으면 부모 클래스의 메서드를 사용한다는 의미가 아닐까 생각됩니다.

**Comment by cherrishRed** [comment]
메서드를 호출 할 때, 먼저 자식 클래스 내부에 그 메서드가 있는지 확인을 한 후에, 그 메서드가 존재하지 않을 경우에 부모 클래스의 메서드를 호출한다 라고 이해 했습니다!

**Comment by kimkyunghun3** [comment]
- 두기: 
```swift
class Person {
    func printSomthing(){
        print("asdf")
    }
}

class Doogie: Person{
}
let doogie = Doogie()
```
위와 같은 클래스가 정의되어 있을 때 서브클래스인 Doogie자체적으로는 printSomthing()라는 메서드는 정의되어 있지 않아 부모클래스로 넘긴다는 의미로 이해함
??? : "야! 두기! printSomthing() 호출해!"
두기 : "이건 내가 스스로 갖고있는건 아닌데 부모클래스한테 위임할게!"

- 에디: super를 호출하는 것이 현재 서브 클래스에서 이 기능을 수행할 수 없거나 이해할 수 없기 때문에 부모 클래스에 위임하는 것이라고 생각합니다. 그래서 이 표현이 메시지를 부모 클래스로 위임시키는 것이 아닐까 싶네요!
